---
apiVersion: v1
kind: Service
metadata:
  name: spark-work-service
  namespace: smartcloud-spark
  labels:
    k8s-app: spark-work
    ver: 2.4.5
spec:
  clusterIP: None
  selector:
    k8s-app: spark-work
    ver: 2.4.5

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-work
  namespace: smartcloud-spark
spec:
  selector:
    matchLabels:
      k8s-app: spark-work
      ver: 2.4.5
  serviceName: "spark-work-service"
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: spark-work
        ver: 2.4.5
    spec:
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: spark-work
          image: 172.27.16.3:9084/xzzh/spark:2.4.5.2
          imagePullPolicy: IfNotPresent
          command:
            - start-spark
            - "worker"
            - "spark-master-0.spark-master-service.smartcloud-spark.svc.cluster.local"
          env:
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_WORKER_MEMORY
              value: "1g"
          volumeMounts:
            - name: hdfs-volume
              mountPath: "/opt/hdfs"
  volumeClaimTemplates:
    - metadata:
        name: hdfs-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: spark-block
        resources:
          requests:
            storage: 10Gi